baseurl: /
markdown: rdiscount
permalink: /:year/:month/:day/:title/
timezone: Asia/beijing

home: http://www.baidu.com/
demo: http://www.baidu.com/
base: http://www.sohu.com
weibo: http://weibo.com/
edit_path: https://github.com/lll19870828/snippets/edit/gh-pages
new_path: https://github.com/lll19870828/snippets/new/gh-pages/snippets
author: jack lee
author_en: Barret Lee
email: lll19870828@sohu.com
author_info: <a href="http://www.baidu.com">jack lee</a>
